name: PHP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.1, 8.2, 8.3]

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: PHP installieren
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, mysqli, pdo, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Composer installieren
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          composer --version

      - name: Abhängigkeiten installieren
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: PHP Lint
        run: find . -type f -name "*.php" -exec php -l {} \;
